### PR TITLE
Some features and optimizations

### PR DESCRIPTION
**Pull request by notmyst33d**
* Native binary size is now smaller
* minSdkVersion is now set to 19 (Android 4.4)
* Added feature that includes archived chats for forwarding messages
* Allocated JVM memory is now 8 GB (builds should be faster)
* Added native.build.cores to set number of cores for native binary building
* Updated dependencies

### CODE REVIEW

**Comment by Playez** [comment]
@notmyst33d

**Comment by Attorelle** [comment]
💟

**Comment by itsreallyv1eds** [comment]
omfg, thx 🙏🙏

**Comment by itsreallyv1eds** [comment]
🥰🥰

**Pull request merged**
