### PR TITLE
Better readme

### PR DESCRIPTION
**Pull request by Suburbanno**

### CODE REVIEW

**Comment by playez** [comment]
@Suburbanno хароош

**Comment by Suburbanno** [comment]
> хароош

EXTERAGRAM

**Comment by playez** [comment]
astronavt-s-pivom

**Comment by Suburbanno** [comment]
Long timeeeeeeee.........

Aug 15, 2023

**Comment by Suburbanno** [comment]
I'll close it, apparently no one gives a shit.

**Pull request closed without merging**
